### ISSUE TITLE
Support for "light" fonts?

### ISSUE THREAD

**Issue by gwerbin** [equalsraf/neovim-gui-shim#2]
Maybe I'm missing something in the docs, but is there a way to select a "light" variant of a font with `:GuiFont`?

**Comment by equalsraf** [comment]
No there isn't but light fonts usually go by a different name so you would need to pass the full name to GuiFont. Did you have any specific font in mind?

**Comment by gwerbin** [comment]
"Source Code Pro for Powerline" is the one I use. If I open the OS X font viewer I can see that "Light" is a style alongside "Italic" and "Bold." 

Currently I'm using `:GuiFont Source Code Pro for Powerline:h14`. I tried `:GuiFont Source Code Pro for Powerline Light:h14` but that didn't work.

**Comment by equalsraf** [comment]
Interesting in gVim setting guifont as Source Code Pro Light doesnt seems to work in my system, but using set guifont=\* its possible to select it. I have no way to check the Macvim behaviour right now, but I see no mention of font weight in the docs.

In neovim-qt it is failing, because of [this line](https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shellwidget/shellwidget.cpp#L45). Removing the line causes the error to go away, but I don't think it works, it seems to be using the regular Source Code Pro instead.

In theory the light font is just the same font with a different weight, much like bold. e.g. [for Qt](http://doc.qt.io/qt-5/qfont.html#Weight-enum), so I guess it makes sense to allow attributes for this, I'm still not sure what would be the GUI behaviour if the the font is not available though.

**Comment by gwerbin** [comment]
I think it should just cause an error and take no action. Or maybe it can fail silently? Or with a warning?
